name: Run Pytest Tests  # CI/CD 流水线名称

on:
  push:  # 当有代码 push 到 GitHub 时触发
    branches:
      - main
  pull_request:  # 触发 pull request 时也执行

jobs:
  test:
    runs-on: ubuntu-latest  # 运行环境（Linux）

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 获取 GitHub 代码

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"  # 设定 Python 版本

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 安装依赖

      - name: Run UI Tests (Selenium)
        run: pytest tests/test_ui.py --alluredir=allure-results || true  # 运行 Selenium UI 测试

      - name: Run API Tests
        run: pytest tests/test_api.py --alluredir=allure-results || true  # 运行 API 测试

      - name: Generate Allure Report
        run: |
          pip install allure-pytest
          allure generate allure-results --clean -o allure-report  # 生成 Allure 测试报告

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report  # 保存测试报告到 GitHub
